<?php

return [
    'default' => [
        'services' => [
            [
                'code' => 'extra_baggage_1kg',
                'type' => 'baggage_increment',
                'label' => 'Extra baggage',
                'description' => 'Additional checked baggage sold in 1 KG increments.',
                'pricing_mode' => 'per_kg',
                'unit_label' => 'KG',
                'unit_price' => 0,
                'default_quantity' => 0,
                'min_quantity' => 0,
                'max_quantity' => 0,
                'command_template' => null,
                'enabled' => true,
            ],
            [
                'code' => 'meal',
                'type' => 'special_service',
                'label' => 'Meal',
                'description' => 'Meal selection depends on airline configuration.',
                'pricing_mode' => 'per_passenger',
                'unit_price' => 0,
                'command_template' => null,
                'enabled' => true,
            ],
            [
                'code' => 'wheelchair',
                'type' => 'special_service',
                'label' => 'Wheelchair assistance',
                'description' => 'Airport assistance service. Configure airline code before sale.',
                'pricing_mode' => 'per_passenger',
                'unit_price' => 0,
                'command_template' => null,
                'enabled' => true,
            ],
            [
                'code' => 'pet_on_board',
                'type' => 'special_service',
                'label' => 'Pet on board',
                'description' => 'Requires airline-specific service code and pricing.',
                'pricing_mode' => 'per_booking',
                'unit_price' => 0,
                'command_template' => null,
                'enabled' => true,
            ],
            [
                'code' => 'visa_preparation',
                'type' => 'special_service',
                'label' => 'Visa preparation',
                'description' => 'Agency service configurable per airline/account.',
                'pricing_mode' => 'per_passenger',
                'unit_price' => 0,
                'command_template' => null,
                'enabled' => true,
            ],
            [
                'code' => 'insurance',
                'type' => 'special_service',
                'label' => 'Insurance',
                'description' => 'Insurance add-on when supported by the airline/account.',
                'pricing_mode' => 'per_passenger',
                'unit_price' => 0,
                'command_template' => null,
                'enabled' => true,
            ],
        ],
    ],
    'YI' => [
        'services' => [
            [
                'code' => 'extra_baggage_1kg',
                'type' => 'baggage_increment',
                'label' => 'Extra baggage',
                'description' => 'Oya ancillary baggage sold in 1 KG increments.',
                'pricing_mode' => 'per_kg',
                'unit_label' => 'KG',
                'unit_price' => 0,
                'default_quantity' => 0,
                'min_quantity' => 0,
                'max_quantity' => 30,
                'command_template' => null,
                'enabled' => true,
            ],
            [
                'code' => 'insurance',
                'type' => 'special_service',
                'label' => 'Insurance',
                'description' => 'Insurance charge can be reconciled from PNR fare/tax lines.',
                'pricing_mode' => 'per_passenger',
                'unit_price' => 0,
                'fare_tax_code' => 'YR',
                'command_template' => null,
                'enabled' => true,
            ],
            [
                'code' => 'wheelchair',
                'type' => 'special_service',
                'label' => 'Wheelchair assistance',
                'description' => 'Selectable when airline-specific command code is configured.',
                'pricing_mode' => 'per_passenger',
                'unit_price' => 0,
                'command_template' => null,
                'enabled' => true,
            ],
            [
                'code' => 'pet_on_board',
                'type' => 'special_service',
                'label' => 'Pet on board',
                'description' => 'Selectable when airline-specific command code is configured.',
                'pricing_mode' => 'per_booking',
                'unit_price' => 0,
                'command_template' => null,
                'enabled' => true,
            ],
            [
                'code' => 'visa_preparation',
                'type' => 'special_service',
                'label' => 'Visa preparation',
                'description' => 'Agency-issued ancillary when command template is configured.',
                'pricing_mode' => 'per_passenger',
                'unit_price' => 0,
                'command_template' => null,
                'enabled' => true,
            ],
        ],
    ],
];
