<?php

return [
    'default' => [
        'services' => [
            [
                'code' => 'extra_baggage_1kg',
                'type' => 'baggage_increment',
                'label' => 'Extra baggage',
                'description' => 'Additional checked baggage.',
                'pricing_mode' => 'per_kg',
                'unit_label' => 'KG',
                'unit_price' => 0,
                'default_quantity' => 0,
                'min_quantity' => 0,
                'max_quantity' => 0,
                'command_template' => null,
                'enabled' => false,
            ],
            [
                'code' => 'meal',
                'type' => 'special_service',
                'label' => 'Meal',
                'description' => 'Meal selection',
                'pricing_mode' => 'per_passenger',
                'unit_price' => 0,
                'command_template' => null,
                'enabled' => false,
            ],
            [
                'code' => 'wheelchair',
                'type' => 'special_service',
                'label' => 'Wheelchair assistance',
                'description' => 'Airport assistance service.',
                'pricing_mode' => 'per_passenger',
                'unit_price' => 0,
                'command_template' => null,
                'enabled' => true,
            ],
            [
                'code' => 'pet_on_board',
                'type' => 'special_service',
                'label' => 'Pet on board',
                'description' => 'Pet on board service.',
                'pricing_mode' => 'per_booking',
                'unit_price' => 0,
                'command_template' => null,
                'enabled' => true,
            ],
            [
                'code' => 'visa_preparation',
                'type' => 'special_service',
                'label' => 'Visa preparation',
                'description' => 'Visa preparation service.',

                'pricing_mode' => 'per_passenger',
                'unit_price' => 0,
                'command_template' => null,
                'enabled' => false,
            ],
            [
                'code' => 'insurance',
                'type' => 'special_service',
                'label' => 'Insurance',
                'description' => 'Insurance add-on.',
                'pricing_mode' => 'per_passenger',
                'unit_price' => 0,
                'command_template' => null,
                'enabled' => false,
            ],
        ],
    ],
    'YI' => [
        'services' => [
            [
                'code' => 'extra_baggage_1kg',
                'type' => 'baggage_increment',
                'label' => 'Extra baggage',
                'description' => 'Additional checked baggage.',
                'pricing_mode' => 'per_kg',
                'unit_label' => 'KG',
                'unit_price' => 0,
                'default_quantity' => 0,
                'min_quantity' => 0,
                'max_quantity' => 30,
                'command_template' => null,
                'enabled' => false,
            ],
            [
                'code' => 'insurance',
                'type' => 'special_service',
                'label' => 'Insurance',
                'description' => 'Insurance add-on.',
                'pricing_mode' => 'per_passenger',
                'unit_price' => 0,
                'fare_tax_code' => 'YR',
                'command_template' => null,
                'enabled' => false,
            ],
            [
                'code' => 'wheelchair',
                'type' => 'special_service',
                'label' => 'Wheelchair assistance',
                'description' => 'Wheelchair assistance service.',
                'pricing_mode' => 'per_passenger',
                'unit_price' => 0,
                'command_template' => null,
                'enabled' => true,
            ],
            [
                'code' => 'pet_on_board',
                'type' => 'special_service',
                'label' => 'Pet on board',
                'description' => 'Pet on board service.',
                'pricing_mode' => 'per_booking',
                'unit_price' => 0,
                'command_template' => null,
                'enabled' => true,
            ],
            [
                'code' => 'visa_preparation',
                'type' => 'special_service',
                'label' => 'Visa preparation',
                'description' => 'Visa preparation service.',
                'pricing_mode' => 'per_passenger',
                'unit_price' => 0,
                'command_template' => null,
                'enabled' => false,
            ],
        ],
    ],
];
